[workspace]
resolver = "2"
members = ["protocol-minimal", "bench"]

[workspace.package]
name = "securedrop-protocol"
version = "0.1.0"
edition = "2024"
authors = ["SecureDrop Team <securedrop@freedom.press>"]
license = "GPL-3.0"
