[package]
name = "securedrop-protocol"
version = "0.1.0"
edition = "2024"
authors = ["redshiftzero <jen@freedom.press>"]
description = "A wip impl of the securedrop protocol"
license = "GPL-3.0"

[dependencies]
libcrux-ed25519 = "0.0.3"
libcrux-curve25519 = "0.0.3"
libcrux-chacha20poly1305 = "0.0.3"
rand_core = {version = "0.6", features = ["getrandom"]}
rand = {version = "0.8", features = ["getrandom"]}
# Needed for wasm compat
getrandom = {version = "0.2", features = ["js"]}
anyhow = "1.0"

[dev-dependencies]
proptest = "1.3"
